### ISSUE TITLE
Missing .initialise() method?

### ISSUE THREAD

**Issue by kastman** [spedemon/occiput#1]
Hey Stefano,

Finally got a chance to start looking at this - aside from a py2 compatability fix for UTF-8 encoding and removing some Siemans mMR "optional" imports, I think this is mostly working: bf5751d7cf5529cb09a75042dfd1a367cfaac3b3.

However I'm confused, because all of the notebooks call a `.initialise()` method directly on the occiput module, but I can't find any initialise in the code. , so this traceback when trying to run the Occiput_PET_pineapple_reconstruct.ipynb (and any others, I assume):

```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-c5bc0595aeaf> in <module>()
      8 
      9 import occiput
---> 10 occiput.initialise()
     11 import numpy
     12 import time

AttributeError: 'module' object has no attribute 'initialise'
```

I must be missing something obvious, but I can't figure it out. Ideas? Thanks,

Erik

**Comment by spedemon** [comment]
Hi Erik, 

The .initialise() method no longer exists. The notebook is not up to date, just remove .initialise(), hopefully everything else is compatible. 
Thanks for fixing the UTF-8 encoding issue. 
The interface to the scanner is messy, it's one of the things I'm re-designing, but have not yet committed any code. 

Stefano

**Comment by kastman** [comment]
Sure, I’ll just keep poking around. Anything else that you can think of that I should remove off the top of your head?

**Comment by kastman** [comment]
Can you help me with Interfiles just a bit? It looks like the Interfile header I have is pretty poor:

```
!INTERFILE := 
!name of data file := Frame3.lst
!PET data type := emission
!study date (dd:mm:yryr) := 06:11:2014
!study time (hh:mm:ss) := 17:54:14
!prescribed duration (sec) := 3600
!tmark count := 18000436
!actual duration (msec) := 3600087
block singles   0 := 26943745 [17996] 26483549 [17998] 9634365 [17999] 0 [17998] 13475 [17996] 0 [17996] 92905 [17998] 3142607401 [17999] 
block singles   ... := 27587406 [17997] 26328490 [17997] 7915773 [17997] 0 [17997] 11043 [17994] 0 [17994] 107884 [17995] 3086105381 [17993] 
block singles   191 := 25079093 [17997] 24403781 [17998] 7620029 [17998] 0 [17997] 10537 [17999] 0 [17995] 99639 [17999] 3190304751 [17999] 
```

The PET Recon is expecting more information, including "total listmode word counts", "image duration", "number of projections", etc.  

Any idea why these listmode headers wouldn't include those things? I looked around in my project and couldn't find anything listing them. Am I missing a basic step to add these in somewhere?

**Comment by spedemon** [comment]
I don't know! The list-mode headers typically look like this: 

!INTERFILE :=
!originating system := 2008
%SMS-MI header name space :=PETLINK 32bit listmode
%SMS-MI version number := 3.2

!GENERAL DATA :=
!data offset in bytes := 0
name of data file := E:\PETQCDATA\PET_ACQ_78_20131212120347-0.l

!GENERAL IMAGE DATA :=
!type of data := PET
%study date (yyyy:mm:dd) := 2013:12:12
%study time (hh:mm:ss GMT+00:00):= 17:06:58
isotope name := F-18
isotope gamma halflife (sec) := 6586.2
isotope branching factor := 0.97
radiopharmaceutical := Fluorodeoxyglucose
relative time of tracer injection (sec) := 0
tracer activity at time of injection (Bq) := 25900000.000000
injected volume (ml):= 0
%tracer injection date (yyyy:mm:dd):=2013:12:12
%tracer injection time (hh:mm:ss GMT+00:00):=16:46:00

%patient orientation := HFS
PET data type := Emission
data format := 
horizontal bed translation := STEPPED
start horizontal bed position (mm) := -17
end horizontal bed position (mm) := -17
start vertical bed position (mm) := 0
number of energy windows := 1
%energy window lower level (keV) [1]:= 430
%energy window upper level (keV) [1]:= 610

!PET STUDY (Emission data) :=
PET scanner type := cylindrical
transaxial FOV diameter (cm) := 59.6
number of rings := 64
distance between rings (cm) := 0.40625
gantry tilt angle (degrees) := 0
gantry crystal radius (cm) := 32.8
bin size (cm) := 0.20445
septa state := none
%number of TOF time bins:= 1
%TOF mashing factor:= 1

!IMAGE DATA DESCRIPTION :=
%preset type := time
%preset value := 900
%preset unit:= seconds
image duration (sec) := 900
%total listmode word counts := 544167649

%COINCIDENCE LIST DATA :=
%LM event and tag words format (bits) := 32
%timing tagwords interval (msec) := 1
%singles polling method := Instantaneous
%singles polling interval (sec) := 2
%singles scale factor := 8
%total number of singles blocks := 224
%axial compression := 1
%maximum ring difference := 60
%number of projections := 344
%number of views := 252
%number of segments := 121
%segment table := { 64, 63, 63, 62, 62, 61, 61, 60, 60, 59, 59, 58, 58, 57, 57, 56, 56, 55, 55, 54, 54, 53, 53, 52, 52, 51, 51, 50, 50, 49, 49, 48, 48, 47, 47, 46, 46, 45, 45, 44, 44, 43, 43, 42, 42, 41, 41, 40, 40, 39, 39, 38, 38, 37, 37, 36, 36, 35, 35, 34, 34, 33, 33, 32, 32, 31, 31, 30, 30, 29, 29, 28, 28, 27, 27, 26, 26, 25, 25, 24, 24, 23, 23, 22, 22, 21, 21, 20, 20, 19, 19, 18, 18, 17, 17, 16, 16, 15, 15, 14, 14, 13, 13, 12, 12, 11, 11, 10, 10,  9,  9,  8,  8,  7,  7,  6,  6,  5,  5,  4,  4}
%time_sync := 17447626
%comment:=PET/CT gantry offset during PET acquisition was x=0.000000mm, y=0.000000mm, z=0.000000mm

**Comment by kastman** [comment]
Ugh, those look completely different. I'll have to bug the folks who I get these from to see if they have any ideas... 

My hunch is that at least some of those will be required to actually reconstruct, so I'm going to stop until I know what's going on with these... Thanks for the sanity check!

**Comment by spedemon** [comment]
The parameters that describe the scanner geometry and the radio-tracer are missing.
